import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react"; 
import { Metadata } from "next"; 
import Navbar from "./component/navbar";
import Footer from "./component/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode; 
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-h-screen max-w-screen overflow-x-hidden`}
      ><Navbar/>
        {children}
        <Footer/>
    
      </body>
    </html>
  );
}
